// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
/// 
/// 
/// 
/// 
/// 
/// 
/// 
/// 
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHe0qMplmqT_zG_TFzTinlIBez3Gw2VfM',
    appId: '1:248475494509:android:946b7aa2dec956681bb764',
    messagingSenderId: '248475494509',
    projectId: 'n2nhrm-91599',
    databaseURL: 'https://n2nhrm-91599-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'n2nhrm-91599.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4lWQC94snjxTOWGsmTOMc5jwb6ICZSTU',
    appId: '1:248475494509:ios:91427237078ea9a21bb764',
    messagingSenderId: '248475494509',
    projectId: 'n2nhrm-91599',
    databaseURL: 'https://n2nhrm-91599-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'n2nhrm-91599.firebasestorage.app',
    iosBundleId: 'com.n2nhrm.apk',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABq4zOpwcdwBTC_Q6Oxjn3fChLs5Rh9Fc',
    appId: '1:248475494509:web:fc36f9be6c0021e61bb764',
    messagingSenderId: '248475494509',
    projectId: 'n2nhrm-91599',
    authDomain: 'n2nhrm-91599.firebaseapp.com',
    databaseURL: 'https://n2nhrm-91599-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'n2nhrm-91599.firebasestorage.app',
  );

}